-- MOSTRAR LA SUMA DE LAS PERSONAS EN TODAS LAS CIUDADES EN ASIA

SELECT SUM(CITY.POPULATION) 
FROM CITY
INNER JOIN COUNTRY ON COUNTRY.CODE = CITY.COUNTRYCODE
WHERE CONTINENT = 'Asia'


-- SELECCIONAR NOMBRE DE CADA CIUDAD EN AFRICA 

SELECT CITY.NAME
FROM CITY
INNER JOIN COUNTRY ON COUNTRY.CODE = CITY.COUNTRYCODE
WHERE CONTINENT = 'Africa'

--IMPRIMIR NOTA DE ESTUDIANTES EN 3 COLUMNAS, NOMBRE GRADO Y NOTA, USANDO CASOS NECESARIOS

SELECT 
    CASE
        WHEN Grades.Grade < 8 THEN NULL
        ELSE Students.Name
    END AS Name,
    Grades.Grade,
    Students.Marks

FROM Students
INNER JOIN Grades ON Students.Marks BETWEEN Grades.Min_Mark AND Grades.Max_Mark
ORDER BY
    Grades.Grade DESC,
    CASE
        WHEN Grades.Grade >= 8 THEN Students.Name
    END ASC,
    CASE
        WHEN Grades.Grade < 8 THEN Students.Marks
    END ASC;
            